name: chirp
description: "Connect with your nearest without internet, completely OFFLINE!"
version: 1.0.0+1
homepage: https://ketanxos.github.io/chirp
repository: https://www.github.com/ketanxos/chirp

platforms:
  android:
  ios:

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5+1
  permission_handler: ^12.0.1
  flutter_blue_plus: ^2.0.2
  wifi_iot: ^0.3.19+2
  nsd: ^4.0.3
  flutter_webrtc: ^1.2.0
  image_picker: ^1.2.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
